In [1]:
# Import our dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# read in cvs as dataframe
suicide_df = pd.read_csv("../Data/socialmedia_mentalhealth.csv")
suicide_df.head()

,country,suicide_year,sex,age_range,suicides_no,population,suicides_100k_pop,country_year,HDI_for_year,gdp_for_year,gdp_per_capita,generation
0,Albania,1987,m,15-24 years,21,312900,6.71,Albania1987,NaN,2156624900,796,Generation X
1,Albania,1987,m,35-54 years,16,308000,5.19,Albania1987,NaN,2156624900,796,Silent
2,Albania,1987,f,15-24 years,14,289700,4.83,Albania1987,NaN,2156624900,796,Generation X
3,Albania,1987,m,75+ years,1,21800,4.59,Albania1987,NaN,2156624900,796,G.I. Generation
4,Albania,1987,m,25-34 years,9,274300,3.28,Albania1987,NaN,2156624900,796,Boomers

In [3]:
# change column name 'suicide_year' to 'year'
suicide_df.rename(columns={'suicide_year': 'year'}, inplace=True)
suicide_df

,country,year,sex,age_range,suicides_no,population,suicides_100k_pop,country_year,HDI_for_year,gdp_for_year,gdp_per_capita,generation
0,Albania,1987,m,15-24 years,21,312900,6.71,Albania1987,NaN,2156624900,796,Generation X
1,Albania,1987,m,35-54 years,16,308000,5.19,Albania1987,NaN,2156624900,796,Silent
2,Albania,1987,f,15-24 years,14,289700,4.83,Albania1987,NaN,2156624900,796,Generation X
3,Albania,1987,m,75+ years,1,21800,4.59,Albania1987,NaN,2156624900,796,G.I. Generation
4,Albania,1987,m,25-34 years,9,274300,3.28,Albania1987,NaN,2156624900,796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,f,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,63067077179,2309,Generation X
27816,Uzbekistan,2014,f,75+ years,9,348465,2.58,Uzbekistan2014,0.675,63067077179,2309,Silent
27817,Uzbekistan,2014,m,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,63067077179,2309,Generation Z
27818,Uzbekistan,2014,f,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,63067077179,2309,Generation Z
27819,Uzbekistan,2014,f,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,63067077179,2309,Boomers

In [4]:
# Remove year 2016 from dataframe and reset the index
first_filter = suicide_df.year != 2016
suicide_df = suicide_df[first_filter]
suicide_df.reset_index(drop=True, inplace=True)
suicide_df

,country,year,sex,age_range,suicides_no,population,suicides_100k_pop,country_year,HDI_for_year,gdp_for_year,gdp_per_capita,generation
0,Albania,1987,m,15-24 years,21,312900,6.71,Albania1987,NaN,2156624900,796,Generation X
1,Albania,1987,m,35-54 years,16,308000,5.19,Albania1987,NaN,2156624900,796,Silent
2,Albania,1987,f,15-24 years,14,289700,4.83,Albania1987,NaN,2156624900,796,Generation X
3,Albania,1987,m,75+ years,1,21800,4.59,Albania1987,NaN,2156624900,796,G.I. Generation
4,Albania,1987,m,25-34 years,9,274300,3.28,Albania1987,NaN,2156624900,796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27655,Uzbekistan,2014,f,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,63067077179,2309,Generation X
27656,Uzbekistan,2014,f,75+ years,9,348465,2.58,Uzbekistan2014,0.675,63067077179,2309,Silent
27657,Uzbekistan,2014,m,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,63067077179,2309,Generation Z
27658,Uzbekistan,2014,f,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,63067077179,2309,Generation Z
27659,Uzbekistan,2014,f,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,63067077179,2309,Boomers

In [7]:
# Create the output file (CSV).
output_data_file = "../Data/cleaned_socialmedia_mentalhealth.csv"
# Export the usage dataframe into a CSV.
suicide_df.to_csv(output_data_file, index = False)